-- liquibase formatted sql

-- changeset onish:1760194522231-1
CREATE TABLE vehicle
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255),
    creation_date      date,
    engine_power       FLOAT                                   NOT NULL,
    number_of_wheels   INTEGER                                 NOT NULL,
    distance_travelled INTEGER                                 NOT NULL,
    fuel_type          VARCHAR(255),
    x                  FLOAT                                   NOT NULL,
    y                  DOUBLE PRECISION,
    CONSTRAINT pk_vehicle PRIMARY KEY (id)
);

